# Generated by Django 3.2.13 on 2022-04-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fegtwitterapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
