# Generated by Django 3.2.13 on 2022-04-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fegtwitterapp', '0003_alter_user_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertweet',
            options={'ordering': ['-upload_date']},
        ),
    ]
