# Generated by Django 3.2.13 on 2022-05-16 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fegtwitterapp', '0004_alter_usertweet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertweet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweetuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
